# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\value_serch.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget, QDialog, QMainWindow
import sys
class Ui_main_form(object):
    def setupUi(self, main_form):
        main_form.setObjectName("main_form")
        main_form.setEnabled(True)
        main_form.resize(359, 1015)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(main_form.sizePolicy().hasHeightForWidth())
        main_form.setSizePolicy(sizePolicy)
        main_form.setMaximumSize(QtCore.QSize(359, 1015))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 68, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 84, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(41, 68, 94))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 84, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(120, 120, 120))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 84, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(50, 84, 115))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 128))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.PlaceholderText, brush)

        main_form.setPalette(palette)
        # main_form.setStyleSheet("color:white;"
        #                                 "background:rgb(31, 52, 71);\nfont: 9pt \"微软雅黑\";")
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(9)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        main_form.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./Icon/exa.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        main_form.setWindowIcon(icon)

        self.checkBox = QtWidgets.QCheckBox(main_form)
        self.checkBox.setGeometry(QtCore.QRect(10, 155, 81, 16))
        self.checkBox.setObjectName("checkBox")
        self.ed1_1 = QtWidgets.QLineEdit(main_form)
        self.ed1_1.setGeometry(QtCore.QRect(278, 150, 36, 22))

        self.ed1_1.setStyleSheet("font: 75 9pt \"微软雅黑\";color:white;background:rgb(31, 52, 71);border-width:1;border-style:none solid none none;")
        self.ed1_1.setCursorPosition(0)
        self.ed1_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ed1_1.setObjectName("ed1_1")
        self.ed1_2 = QtWidgets.QLineEdit(main_form)
        self.ed1_2.setGeometry(QtCore.QRect(314, 150, 36, 22))

        self.ed1_2.setStyleSheet("font: 75 9pt \"微软雅黑\";color:white;background:rgb(31, 52, 71);border-width:0;border-style:none none none solid ;")
        self.ed1_2.setCursorPosition(0)
        self.ed1_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ed1_2.setObjectName("ed1_2")
        self.state_fram = QtWidgets.QFrame(main_form)
        self.state_fram.setGeometry(QtCore.QRect(0, 190, 361, 311))
        self.state_fram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.state_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.state_fram.setObjectName("state_fram")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.state_fram)
        self.verticalLayout.setObjectName("verticalLayout")
        self.state1 = QtWidgets.QFrame(self.state_fram)
        self.state1.setAutoFillBackground(False)
        self.state1.setStyleSheet("color:white;border-width:1 ;border-style:none none solid none;border-color:rgb(150, 150, 150);\n"
"font: 9pt \"微软雅黑\";")
        self.state1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.state1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.state1.setObjectName("state1")
        self.checkBox_2 = QtWidgets.QCheckBox(self.state1)
        self.checkBox_2.setGeometry(QtCore.QRect(0, 10, 271, 18))
        self.checkBox_2.setStyleSheet("color:white;border-width:1 ;border-style:none none none none;border-color:rgb(150, 150, 150);\n"
"font: 9pt \"微软雅黑\";")
        self.checkBox_2.setChecked(True)
        self.checkBox_2.setObjectName("checkBox_2")
        self.ed2_2 = QtWidgets.QLineEdit(self.state1)
        self.ed2_2.setGeometry(QtCore.QRect(304, 10, 36, 22))

        self.ed2_2.setStyleSheet("color:white;background:rgb(31, 52, 71);border-width:0;border-style:none none none solid ;font: 75 9pt \"微软雅黑\";")
        self.ed2_2.setCursorPosition(0)
        self.ed2_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ed2_2.setObjectName("ed2_2")
        self.ed2_1 = QtWidgets.QLineEdit(self.state1)
        self.ed2_1.setGeometry(QtCore.QRect(268, 10, 36, 22))

        self.ed2_1.setStyleSheet("color:white;background:rgb(31, 52, 71);border-width:1;border-style:none solid none none;border-color:black;\n"
"font: 75 9pt \"微软雅黑\";")
        self.ed2_1.setCursorPosition(0)
        self.ed2_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ed2_1.setObjectName("ed2_1")
        self.verticalLayout.addWidget(self.state1)
        self.state2 = QtWidgets.QFrame(self.state_fram)
        self.state2.setStyleSheet("color:white;border-width:1 ;border-style:none none solid none;border-color:rgb(150, 150, 150);\n"
"font: 9pt \"微软雅黑\";")
        self.state2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.state2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.state2.setObjectName("state2")
        self.checkBox_3 = QtWidgets.QCheckBox(self.state2)
        self.checkBox_3.setGeometry(QtCore.QRect(0, 10, 271, 18))
        self.checkBox_3.setStyleSheet("color:white;border-width:1 ;border-style:none none none none;border-color:rgb(150, 150, 150);\n"
"font: 9pt \"微软雅黑\";")
        self.checkBox_3.setObjectName("checkBox_3")
        self.ed3_2 = QtWidgets.QLineEdit(self.state2)
        self.ed3_2.setGeometry(QtCore.QRect(304, 10, 36, 22))

        self.ed3_2.setStyleSheet("color:white;background:rgb(31, 52, 71);border-width:0;border-style:none none none solid ;font: 75 9pt \"微软雅黑\";")
        self.ed3_2.setCursorPosition(0)
        self.ed3_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ed3_2.setObjectName("ed3_2")
        self.ed3_1 = QtWidgets.QLineEdit(self.state2)
        self.ed3_1.setGeometry(QtCore.QRect(268, 10, 36, 22))

        self.ed3_1.setStyleSheet("color:white;background:rgb(31, 52, 71);border-width:1;border-style:none solid none none;border-color:black;\n"
"font: 75 9pt \"微软雅黑\";")
        self.ed3_1.setCursorPosition(0)
        self.ed3_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ed3_1.setObjectName("ed3_1")
        self.verticalLayout.addWidget(self.state2)
        self.state3 = QtWidgets.QFrame(self.state_fram)
        self.state3.setStyleSheet("color:white;border-width:1 ;border-style:none none solid none;border-color:rgb(150, 150, 150);\n"
"font: 9pt \"微软雅黑\";")
        self.state3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.state3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.state3.setObjectName("state3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.state3)
        self.checkBox_4.setGeometry(QtCore.QRect(0, 10, 271, 18))
        self.checkBox_4.setStyleSheet("color:white;border-width:1 ;border-style:none none none none;border-color:rgb(150, 150, 150);\n"
"font: 9pt \"微软雅黑\";")
        self.checkBox_4.setObjectName("checkBox_4")
        self.ed4_2 = QtWidgets.QLineEdit(self.state3)
        self.ed4_2.setGeometry(QtCore.QRect(304, 10, 36, 22))

        self.ed4_2.setStyleSheet("color:white;background:rgb(31, 52, 71);border-width:0;border-style:none none none solid ;font: 75 9pt \"微软雅黑\";")
        self.ed4_2.setCursorPosition(0)
        self.ed4_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ed4_2.setObjectName("ed4_2")
        self.ed4_1 = QtWidgets.QLineEdit(self.state3)
        self.ed4_1.setGeometry(QtCore.QRect(268, 10, 36, 22))

        self.ed4_1.setStyleSheet("color:white;background:rgb(31, 52, 71);border-width:1;border-style:none solid none none;border-color:black;\n"
"font: 75 9pt \"微软雅黑\";")
        self.ed4_1.setCursorPosition(0)
        self.ed4_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ed4_1.setObjectName("ed4_1")
        self.verticalLayout.addWidget(self.state3)
        self.state4 = QtWidgets.QFrame(self.state_fram)
        self.state4.setStyleSheet("color:white;border-width:1 ;border-style:none none solid none;border-color:rgb(150, 150, 150);\n"
"font: 9pt \"微软雅黑\";")
        self.state4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.state4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.state4.setObjectName("state4")
        self.checkBox_5 = QtWidgets.QCheckBox(self.state4)
        self.checkBox_5.setGeometry(QtCore.QRect(0, 10, 271, 18))
        self.checkBox_5.setStyleSheet("color:white;border-width:1 ;border-style:none none none none;border-color:rgb(150, 150, 150);\n"
"font: 9pt \"微软雅黑\";")
        self.checkBox_5.setObjectName("checkBox_5")
        self.ed5_2 = QtWidgets.QLineEdit(self.state4)
        self.ed5_2.setGeometry(QtCore.QRect(304, 10, 36, 22))

        self.ed5_2.setStyleSheet("color:white;background:rgb(31, 52, 71);border-width:0;border-style:none none none solid ;font: 75 9pt \"微软雅黑\";")
        self.ed5_2.setCursorPosition(0)
        self.ed5_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ed5_2.setObjectName("ed5_2")
        self.ed5_1 = QtWidgets.QLineEdit(self.state4)
        self.ed5_1.setGeometry(QtCore.QRect(268, 10, 36, 22))

        self.ed5_1.setStyleSheet("color:white;background:rgb(31, 52, 71);border-width:1;border-style:none solid none none;border-color:black;\n"
"font: 75 9pt \"微软雅黑\";")
        self.ed5_1.setCursorPosition(0)
        self.ed5_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ed5_1.setObjectName("ed5_1")
        self.verticalLayout.addWidget(self.state4)
        self.state5 = QtWidgets.QFrame(self.state_fram)
        self.state5.setStyleSheet("color:white;border-width:1 ;border-style:none none solid none;border-color:rgb(150, 150, 150);\n"
"font: 9pt \"微软雅黑\";")
        self.state5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.state5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.state5.setObjectName("state5")
        self.checkBox_6 = QtWidgets.QCheckBox(self.state5)
        self.checkBox_6.setGeometry(QtCore.QRect(0, 10, 271, 18))
        self.checkBox_6.setStyleSheet("color:white;border-width:1 ;border-style:none none none none;border-color:rgb(150, 150, 150);\n"
"font: 9pt \"微软雅黑\";")
        self.checkBox_6.setObjectName("checkBox_6")
        self.ed6_2 = QtWidgets.QLineEdit(self.state5)
        self.ed6_2.setGeometry(QtCore.QRect(304, 10, 36, 22))

        self.ed6_2.setStyleSheet("color:white;background:rgb(31, 52, 71);border-width:0;border-style:none none none solid ;font: 75 9pt \"微软雅黑\";")
        self.ed6_2.setCursorPosition(0)
        self.ed6_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ed6_2.setObjectName("ed6_2")
        self.ed6_1 = QtWidgets.QLineEdit(self.state5)
        self.ed6_1.setGeometry(QtCore.QRect(268, 10, 36, 22))

        self.ed6_1.setStyleSheet("color:white;background:rgb(31, 52, 71);border-width:1;border-style:none solid none none;border-color:black;\n"
"font: 75 9pt \"微软雅黑\";")
        self.ed6_1.setCursorPosition(0)
        self.ed6_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ed6_1.setObjectName("ed6_1")
        self.verticalLayout.addWidget(self.state5)
        self.state6 = QtWidgets.QFrame(self.state_fram)
        self.state6.setStyleSheet("color:white;border-width:1 ;border-style:none none solid none;border-color:rgb(150, 150, 150);\n"
"font: 9pt \"微软雅黑\";")
        self.state6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.state6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.state6.setObjectName("state6")
        self.checkBox_7 = QtWidgets.QCheckBox(self.state6)
        self.checkBox_7.setGeometry(QtCore.QRect(0, 10, 271, 18))
        self.checkBox_7.setStyleSheet("color:white;border-width:1 ;border-style:none none none none;border-color:rgb(150, 150, 150);\n"
"font: 9pt \"微软雅黑\";")
        self.checkBox_7.setObjectName("checkBox_7")
        self.ed7_2 = QtWidgets.QLineEdit(self.state6)
        self.ed7_2.setGeometry(QtCore.QRect(304, 10, 36, 22))

        self.ed7_2.setStyleSheet("color:white;background:rgb(31, 52, 71);border-width:0;border-style:none none none solid ;font: 75 9pt \"微软雅黑\";")
        self.ed7_2.setCursorPosition(0)
        self.ed7_2.setAlignment(QtCore.Qt.AlignCenter)
        self.ed7_2.setObjectName("ed7_2")
        self.ed7_1 = QtWidgets.QLineEdit(self.state6)
        self.ed7_1.setGeometry(QtCore.QRect(268, 10, 36, 22))

        self.ed7_1.setStyleSheet("color:white;background:rgb(31, 52, 71);border-width:1;border-style:none solid none none;border-color:black;\n"
"font: 75 9pt \"微软雅黑\";")
        self.ed7_1.setCursorPosition(0)
        self.ed7_1.setAlignment(QtCore.Qt.AlignCenter)
        self.ed7_1.setObjectName("ed7_1")
        self.verticalLayout.addWidget(self.state6)
        self.line = QtWidgets.QFrame(main_form)
        self.line.setGeometry(QtCore.QRect(10, 180, 340, 1))
        self.line.setStyleSheet("background-color:rgb(150, 150, 150)")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.obj_fram = QtWidgets.QFrame(main_form)
        self.obj_fram.setGeometry(QtCore.QRect(10, 60, 341, 25))
        self.obj_fram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.obj_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.obj_fram.setObjectName("obj_fram")
        self.category_label = QtWidgets.QLabel(self.obj_fram)
        self.category_label.setGeometry(QtCore.QRect(10, 5, 141, 16))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.category_label.setFont(font)
        self.category_label.setObjectName("category_label")
        self.objname_ckbox = QtWidgets.QCheckBox(self.obj_fram)
        self.objname_ckbox.setGeometry(QtCore.QRect(220, 5, 111, 16))
        self.objname_ckbox.setObjectName("objname_ckbox")
        self.update_tbrow = QtWidgets.QTextBrowser(main_form)
        self.update_tbrow.setGeometry(QtCore.QRect(10, 10, 341, 46))
        self.update_tbrow.setStyleSheet("border-radius: 6px;;color:white;background:rgb(31, 52, 71);border-width:1;"
                                        "border-style:none solid none none;font: 11pt \"微软雅黑\";")
        self.update_tbrow.setObjectName("update_tbrow")
        self.uncheck_but = QtWidgets.QPushButton(main_form)
        self.uncheck_but.setGeometry(QtCore.QRect(10, 505, 75, 23))
        self.uncheck_but.setObjectName("uncheck_but")
        self.search_but = QtWidgets.QPushButton(main_form)
        self.search_but.setGeometry(QtCore.QRect(140, 505, 75, 23))
        self.search_but.setObjectName("search_but")

        self.base_attr_fram = QtWidgets.QFrame(main_form)
        self.base_attr_fram.setGeometry(QtCore.QRect(10, 90, 341, 61))
        self.base_attr_fram.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.base_attr_fram.setFrameShadow(QtWidgets.QFrame.Raised)
        self.base_attr_fram.setObjectName("base_attr_fram")
        self.base_attr_fram.setWindowOpacity(0)
        # self.gridLayout = QtWidgets.QGridLayout(self.base_attr_fram)
        # self.gridLayout.setObjectName("gridLayout")
        # self.gridLayout.totalMaximumSize()
        self.white_num_lab = QtWidgets.QLabel(self.base_attr_fram)
        # self.white_num_lab.setGeometry(QtCore.QRect(0, 10, 51, 21))

        self.white_num_lab.setFont(font)
        self.white_num_lab.setStyleSheet("border-radius: 6px;  border:1px solid white;color:white;background:"
                                         "rgb(31, 52, 71);\nfont: 9pt \"微软雅黑\";")
        self.white_num_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.white_num_lab.setObjectName("white_num_lab")
        # self.gridLayout.addWidget(self.white_num_lab, 0, 0, 1, 1)
        self.item_level_lab = QtWidgets.QLabel(self.base_attr_fram)
        self.item_level_lab.setGeometry(QtCore.QRect(70, 10, 81, 21))

        self.item_level_lab.setFont(font)
        #
        self.item_level_lab.setStyleSheet("border-radius: 6px;  border:1px solid white;color:white;"
                                          "background:rgb(31, 52, 71);\nfont: 9pt \"微软雅黑\";")
        self.item_level_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.item_level_lab.setObjectName("item_level_lab")
        self.max_link_lab = QtWidgets.QLabel(self.base_attr_fram)
        self.max_link_lab.setGeometry(QtCore.QRect(200, 10, 51, 21))

        self.max_link_lab.setStyleSheet("border-radius: 6px;  border:1px solid white;color:white;"
                                        "background:rgb(31, 52, 71);\nfont: 9pt \"微软雅黑\";")
        self.max_link_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.max_link_lab.setObjectName("max_link_lab")
        self.hunter_lab = QtWidgets.QLabel(self.base_attr_fram)
        self.hunter_lab.setGeometry(QtCore.QRect(10, 30, 61, 21))

        self.hunter_lab.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.hunter_lab.setAutoFillBackground(False)
        self.hunter_lab.setStyleSheet("border-radius: 6px;  border:1px solid white;color:white;"
                                      "background:rgb(31, 52, 71);"
                                      "\nbackground-image: url(:/hunter/power_image/hunter-symbol.png);\n"
                                      "font: 11pt \"微软雅黑\";background-repeat: no-repeat;\n")
        self.hunter_lab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.hunter_lab.setTextFormat(QtCore.Qt.RichText)
        self.hunter_lab.setScaledContents(True)
        self.hunter_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.hunter_lab.setWordWrap(False)
        self.hunter_lab.setIndent(0)
        self.hunter_lab.setOpenExternalLinks(False)
        self.hunter_lab.setObjectName("hunter_lab")
        self.shaper_lab = QtWidgets.QLabel(self.base_attr_fram)
        self.shaper_lab.setGeometry(QtCore.QRect(70, 30, 61, 21))

        self.shaper_lab.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.shaper_lab.setAutoFillBackground(False)
        self.shaper_lab.setStyleSheet("border-radius: 6px;  border:1px solid white;color:white;"
                                      "background:rgb(31, 52, 71);\n"
                                      "background-image: url(:/shaper/power_image/shaper-symbol.png);\n"
                                      "font: 11pt \"微软雅黑\";background-repeat: no-repeat;\n")
        self.shaper_lab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.shaper_lab.setTextFormat(QtCore.Qt.RichText)
        self.shaper_lab.setScaledContents(True)
        self.shaper_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.shaper_lab.setWordWrap(False)
        self.shaper_lab.setIndent(0)
        self.shaper_lab.setOpenExternalLinks(False)
        self.shaper_lab.setObjectName("shaper_lab")
        # self.shaper_lab.adjustSize()
        self.redeemer_lab = QtWidgets.QLabel(self.base_attr_fram)
        self.redeemer_lab.setGeometry(QtCore.QRect(130, 30, 61, 21))

        self.redeemer_lab.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.redeemer_lab.setAutoFillBackground(False)
        self.redeemer_lab.setStyleSheet("border-radius: 6px;  border:1px solid white;color:white;"
                                        "background:rgb(31, 52, 71);\n"
                                        "background-image: url(:/reedemer/power_image/redeemer-symbol.png);\n"
                                        "font: 11pt \"微软雅黑\";background-repeat: no-repeat;\n")
        self.redeemer_lab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.redeemer_lab.setTextFormat(QtCore.Qt.RichText)
        self.redeemer_lab.setScaledContents(True)
        self.redeemer_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.redeemer_lab.setWordWrap(False)
        self.redeemer_lab.setIndent(0)
        self.redeemer_lab.setOpenExternalLinks(False)
        self.redeemer_lab.setObjectName("redeemer_lab")
        self.warlorder_lab = QtWidgets.QLabel(self.base_attr_fram)
        self.warlorder_lab.setGeometry(QtCore.QRect(190, 30, 61, 21))

        self.warlorder_lab.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.warlorder_lab.setAutoFillBackground(False)
        self.warlorder_lab.setStyleSheet("border-radius: 6px;  border:1px solid white;color:white;"
                                         "background:rgb(31, 52, 71);\n"
                                         "background-image: url(:/warlord/power_image/warlord-symbol.png);\n"
                                         "font: 11pt \"微软雅黑\";background-repeat: no-repeat;\n")
        self.warlorder_lab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.warlorder_lab.setTextFormat(QtCore.Qt.RichText)
        self.warlorder_lab.setScaledContents(True)
        self.warlorder_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.warlorder_lab.setWordWrap(False)
        self.warlorder_lab.setIndent(0)
        self.warlorder_lab.setOpenExternalLinks(False)
        self.warlorder_lab.setObjectName("warlorder_lab")
        self.crosader_lab = QtWidgets.QLabel(self.base_attr_fram)
        self.crosader_lab.setGeometry(QtCore.QRect(250, 30, 61, 21))

        self.crosader_lab.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.crosader_lab.setAutoFillBackground(False)
        self.crosader_lab.setStyleSheet("border-radius: 6px;  border:1px solid white;color:white;"
                                        "background:rgb(31, 52, 71);\n"
                                        "background-image: url(:/pic/power_image/crusader-symbol.png);\n"
                                        "font: 11pt \"微软雅黑\";background-repeat: no-repeat;\n")

        self.crosader_lab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.crosader_lab.setTextFormat(QtCore.Qt.RichText)
        self.crosader_lab.setScaledContents(True)
        self.crosader_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.crosader_lab.setWordWrap(False)
        self.crosader_lab.setIndent(0)
        self.crosader_lab.setOpenExternalLinks(False)
        self.crosader_lab.setObjectName("crosader_lab")
        self.elder_lab = QtWidgets.QLabel(self.base_attr_fram)
        self.elder_lab.setGeometry(QtCore.QRect(250, 10, 61, 21))

        self.elder_lab.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.elder_lab.setAutoFillBackground(False)
        self.elder_lab.setStyleSheet("border-radius: 6px;  border:1px solid white;color:white;"
                                     "background:rgb(31, 52, 71);\n"
                                     "background-image:url(:/elder/power_image/elder-symbol.png);\n"
                                     "font: 11pt \"微软雅黑\";background-repeat: no-repeat;\n")
        self.elder_lab.setFrameShadow(QtWidgets.QFrame.Plain)
        self.elder_lab.setTextFormat(QtCore.Qt.RichText)
        self.elder_lab.setScaledContents(True)
        self.elder_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.elder_lab.setWordWrap(False)
        self.elder_lab.setIndent(0)
        self.elder_lab.setOpenExternalLinks(False)
        self.elder_lab.setObjectName("elder_lab")
        self.is_pollution_lab = QtWidgets.QLabel(self.base_attr_fram)
        self.is_pollution_lab.setGeometry(QtCore.QRect(150, 10, 51, 21))

        self.is_pollution_lab.setStyleSheet("border-radius: 6px;  border:1px solid white;color:white;"
                                            "background:rgb(31, 52, 71);\nfont: 9pt \"微软雅黑\";")
        self.is_pollution_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.is_pollution_lab.setObjectName("is_pollution_lab")
        self.quality_lab = QtWidgets.QLabel(self.base_attr_fram)
        self.quality_lab.setGeometry(QtCore.QRect(40, 10, 51, 21))

        self.quality_lab.setStyleSheet("border-radius: 6px;  border:1px solid white;color:white;"
                                       "background:rgb(31, 52, 71);\nfont: 9pt \"微软雅黑\";")
        self.quality_lab.setAlignment(QtCore.Qt.AlignCenter)
        self.quality_lab.setObjectName("quality_lab")
        self.frame = QtWidgets.QFrame(main_form)
        self.frame.setGeometry(QtCore.QRect(10, 530, 340, 20))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(0, 2, 61, 16))
        self.label.setObjectName("label")
        self.search_but_2 = QtWidgets.QPushButton(self.frame)
        self.search_but_2.setGeometry(QtCore.QRect(260, 0, 81, 23))
        self.search_but_2.setObjectName("search_but_2")
        self.search_but_3 = QtWidgets.QPushButton(main_form)
        self.search_but_3.setGeometry(QtCore.QRect(276, 505, 75, 23))
        self.search_but_3.setObjectName("search_but_3")

        self.retranslateUi(main_form)
        QtCore.QMetaObject.connectSlotsByName(main_form)

    def retranslateUi(self, main_form):
        _translate = QtCore.QCoreApplication.translate
        main_form.setWindowTitle(_translate("main_form", "Path of Trade"))

        self.checkBox.setText(_translate("main_form", "CheckBox"))
        self.checkBox_2.setText(_translate("main_form", "CheckBox"))
        self.checkBox_3.setText(_translate("main_form", "CheckBox"))
        self.checkBox_4.setText(_translate("main_form", "CheckBox"))
        self.checkBox_5.setText(_translate("main_form", "CheckBox"))
        self.checkBox_6.setText(_translate("main_form", "CheckBox"))
        self.checkBox_7.setText(_translate("main_form", "CheckBox"))
        self.category_label.setText(_translate("main_form", "物品类别："))
        self.objname_ckbox.setText(_translate("main_form", "CheckBox"))
        self.update_tbrow.setHtml(_translate("main_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'微软雅黑\'; font-size:11pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">车位</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">的违法</span></p></body></html>"))
        self.uncheck_but.setText(_translate("main_form", "取消选中"))
        self.search_but.setText(_translate("main_form", "查询"))
        self.white_num_lab.setText(_translate("main_form", "白孔:"))
        self.item_level_lab.setText(_translate("main_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:10px; margin-right:10px; -qt-block-indent:0; text-indent:0px;display:block;\"><span style=\" font-family:\'微软雅黑\';\">物品等级：</span></p></body></html>"))
        self.item_level_lab.adjustSize()
        self.max_link_lab.setText(_translate("main_form", "链接:"))
        self.hunter_lab.setText(_translate("main_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:15px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\';\">狩猎者</span></p></body></html>"))
        self.shaper_lab.setText(_translate("main_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:15px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\';\">塑界者</span></p></body></html>"))
        self.redeemer_lab.setText(_translate("main_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:15px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\';\">救赎者</span></p></body></html>"))
        self.warlorder_lab.setText(_translate("main_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:12px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\';\">督军</span></p></body></html>"))
        self.crosader_lab.setText(_translate("main_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:15px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\';\">圣战者</span></p></body></html>"))
        self.elder_lab.setText(_translate("main_form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:15px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'微软雅黑\';\">裂界者</span></p></body></html>"))
        self.is_pollution_lab.setText(_translate("main_form", "未腐化"))
        self.quality_lab.setText(_translate("main_form", "品质:"))
        self.label.setText(_translate("main_form", "匹配数:"))
        self.search_but_2.setText(_translate("main_form", "打开网页市集"))
        self.search_but_3.setText(_translate("main_form", "词缀纠错"))
import icon_rc
class main_fram(object):
    def __init__(self):
        self.ui = Ui_main_form()
        self.main_fram = QMainWindow()
        self.ui.setupUi(self.main_fram)
        self.main_fram.show()

# app = QApplication(sys.argv)
# main_fram = QMainWindow()
# ui = Ui_main_form()
# ui.setupUi(main_fram)
# main_fram.show()
#
# sys.exit(app.exec_())
